<?php
use Laminas\Session\Container;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();

$referer = $_SERVER['HTTP_REFERER'] ?? null;
//last search 
$searchReferer = "";
if ($referer && str_contains($referer, 'q=')) {
    $searchReferer = $referer;
}

if($template):
  $type = $template->label();
else:
  $type = "";
endif;

$thumb = $item->primaryMedia();

$old_titles = $item->value('dcterms:replaces',array('all'=>true));
foreach($old_titles as $old_title):
  preg_match('#\((.*?)\)#', $old_title.'', $match);
  $old_title = explode("-",$match[1]);  
endforeach;  

if($type == 'Ledenblad'):
  $title = $resource->displayTitle();
  $title = explode(", ",$title);
  $date = $title[1];
  $title = explode(":",$title[2]);
  $nr = $title[0];
  $title = $title[1];
  //check if title is correct
  $old_titles = $item->value('dcterms:replaces',array('all'=>true));
  foreach($old_titles as $old_title):
    preg_match('#\((.*?)\)#', $old_title.'', $match);
    $dates = explode("-",$match[1]);
    if($date >= $dates[0] && $date <= $dates[1]):
      $title = $old_title.'';
    endif;  
  endforeach;  
  $title = trim($title).", ".$date.", ".$nr;
else:
  $title = $resource->displayTitle();
endif;  
?>

<!-- beeldbank: image / table -->
<div class="section section--default">
  <div class="container">
    <div class="breadcrumb spacer">
        <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
            <a href="<?php echo $site->url();?>" itemprop="url" class="breadcrumb__item"><span itemprop="title">Home</span></a>
        </span>
        <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
          <?php if($searchReferer):?>
            <a href="<?= htmlspecialchars($searchReferer) ?>" itemprop="url" class="breadcrumb__item"><span itemprop="title">Zoekresultaten</span></a>
          <?php elseif($type == "Beeld"): ?>
            <a href="/beeldbank?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">Beeldbank</span></a>
          <?php elseif($type == "Collectie"):?>
            <a href="/collecties?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">Collectie</span></a>
          <?php elseif($type == "Nieuws"):?>
            <a href="/nieuws?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">Nieuws</span></a>
          <?php elseif($type == "Agendapunt"):?>
            <a href="/agenda?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">Agenda</span></a>
          <?php elseif($type == "Film"):?>
            <a href="/films?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">Films</span></a>
          <?php elseif($type == "Filmkopie"):?>
            <a href="/filmkopies?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">Filmkopies</span></a>
          <?php elseif($type == "Ledenblad"):?>
            <a href="/s/start/ledenbladen?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">Ledenbladen</span></a>
          <?php endif;?>
        </span>
        <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
            <span itemprop="title"><?php echo $title;?></span>
        </span>
    </div>
    <h1><?php echo $this->pageTitle($title, 2); ?></h1>



    <?php if($item->value('dcterms:date') && ($type == 'Nieuws' || $type == 'Agendapunt')):?>
        <?php
          $date = $item->value('dcterms:date');
          //echo $date;
          $output = DateTime::createFromFormat('Ymd', $date);
          if(!$output){
              $output = DateTime::createFromFormat('Y-m-d', $date);
          }
          $output = $output->format('d-m-Y');
        ?>
        <p class="datering"><?php echo $output;?></p>
    <?php endif;?>
  </div>
</div>



<?php $this->trigger('view.show.before'); ?>

<!-- Beeld centered -->
<?php if($type == "Beeld"): ?>
  <?php if ($embedMedia && $itemMedia): ?>
    <div class="section section--default">
      <div class="container">
        <!-- beeld -->
        <?php if(sizeof($itemMedia) > 1):?>
          <div class="slider-for">
            <?php foreach($itemMedia as $media):?>
              <div class="beeld">
                <?php
                  $url = str_replace('http:', '', $media->thumbnailUrl('large'));
                ?>
                <img src="<?php echo $url;?>">
              </div>
            <?php endforeach;?>
          </div>
          <div class="slider-nav" role="toolbar">
            <?php foreach($itemMedia as $media):?>
              <div class="beeld-nav">
                <?php
                  $url = str_replace('http:', '', $media->thumbnailUrl('square'));
                ?>
                <img src="<?php echo $url;?>">
              </div>
            <?php endforeach;?>
          </div>
        <?php else: ?>
          <div class="beeld">
            <?php $url = str_replace('http:', '', $itemMedia[0]->thumbnailUrl('large'));?>
            <img src="<?php echo $url;?>">
          </div>
        <?php endif;?>
      </div>
    </div>
  <?php endif; ?>
  <div class="section section--default">
    <div class="container">
      <div class="panel panel--light">
        <p><?php echo $item->displayDescription(); ?></p>
      </div>
    </div>
  </div>
<?php endif?>

<?php if($type == "Film" || $type == "Filmkopie"): ?>
  <?php if ($embedMedia && $itemMedia): ?>
    <div class="section section--default">
      <div class="container">
        <!-- beeld -->
        <?php if(sizeof($itemMedia) > 1):?>
          <div class="slider-for">
            <?php foreach($itemMedia as $media):?>
              <div class="beeld">
                <?php
                  echo $media->render();
                ?>
              </div>
            <?php endforeach;?>
          </div>
          <div class="slider-nav" role="toolbar">
            <?php foreach($itemMedia as $media):?>
              <div class="beeld-nav">
                <?php
                  $url = str_replace('http:', '', $media->thumbnailUrl('square'));
                ?>
                <img src="<?php echo $url;?>">
              </div>
            <?php endforeach;?>
          </div>
        <?php else: ?>
          <div class="beeld">
            <?php
              echo $itemMedia[0]->render();
            ?>
          </div>
        <?php endif;?>
      </div>
    </div>

  <?php endif; ?>
  
  <?php $frames = $item->value('dcterms:hasVersion',array('all'=>true));?>
  <?php if($frames || $item->value('dcterms:accrualPeriodicity')):?>   
    <div class="section section--default">   
      <div class="container" style="margin-top:2rem;">   
        <?php if($frames):?>            
          <?php foreach($frames as $frame):?>
            <?php if (filter_var($frame, FILTER_VALIDATE_URL)) { ?>                
              <a target="_blank" href="<?php echo $frame;?>" class="btn btn--ext" style="margin-right:5px;">
                Bekijk de film
              </a>                    
            <?php } ?>  
          <?php endforeach;?>
        <?php endif;?>     

        <?php if($item->value('dcterms:accrualPeriodicity')):?>
          <a target="_blank" href="<?php echo $item->value('dcterms:accrualPeriodicity');?>" class="btn btn--ext">     
        Raadpleeg het archief</a>
        <?php endif;?>            
      </div>
    </div>  
  <?php endif;?>  
    
  <?php if($item->displayDescription()):?>
    <div class="section section--default">
      <div class="container">
        <div class="panel panel--light">
          <p><?php echo $item->displayDescription(); ?></p>
        </div>
      </div>
    </div>
  <?php endif; ?>
<?php endif?>

<!-- 2 columns if not Beeld and has thumbnail -->
<?php if($type != "Beeld" && $type != "Film" && $thumb && $type != "Ledenblad"): ?>
  <div class="section section--default">
    <div class="container">
      <div class="grid grid--2-col@med">
        <div class="grid__item">
          <div class="text-description">
          <?php echo $item->displayDescription(); ?>
          </div>
        </div>
        <div class="grid__item">
          <?php if(sizeof($itemMedia) > 1):?>
            <div class="slider-for">
              <?php foreach($itemMedia as $media):?>
                <div class="beeld">
                  <?php
                    $render =  $media->render();
                    $render = str_replace('http:', '', $render);
                    echo $render;
                    //$url = str_replace('http:', '', $media->thumbnailUrl('large'));
                  ?>
                  <!--<img src="<?php echo $url;?>">-->
                </div>
              <?php endforeach;?>
            </div>
            <div class="slider-nav" role="toolbar">
              <?php foreach($itemMedia as $media):?>
                <div class="beeld-nav">
                  <?php
                    $url = str_replace('http:', '', $media->thumbnailUrl('square'));
                  ?>
                  <img src="<?php echo $url;?>">
                </div>
              <?php endforeach;?>
            </div>
          <?php else: ?>
            <div class="beeld">
              <?php
                if($item->value('dcterms:identifier')):
                else:  
                  $render =  $itemMedia[0]->render();
                  $render = str_replace('http:', '', $render);
                  echo $render;
                endif;
              ?>
              <!--<img src="<?php echo $url;?>">-->
            </div>
          <?php endif;?>
               <?php //echo $this->thumbnail($thumb, 'large');?>
        </div>
      </div>
    </div>
  </div>
<?php endif; ?>
<?php if($type == "Ledenblad"):?>
<div class="section section--default">
    <?php if(sizeof($itemMedia) > 1):?>
      <?php
        $web_query="";        
        if(isset($_GET["q"])):  
          $web_query = "&searchText=".htmlspecialchars(strip_tags($_GET["q"]));          
          $count = str_word_count($web_query);
          //echo $web_query;
        endif;
      ?>
      <?php $this->trigger('view.show.after'); ?>
    <?php endif;?>  
</div>
<?php endif;?>  

<?php if($type != 'Nieuws' && $type != 'Agendapunt'):?>
<div class="section section--default">
  <div class="container">
        <?php if($type == "Collectie"):?>
          <h2>Praktische info</h2>
        <?php endif;?>
        <span> <!-- content text must be in a wrapper if it's directly in a grid__item -->
            <table class="">
                <tbody>
                  <?php echo $item->displayValues(); ?>
                  <?php if($type == 'Ledenblad'):?>
                    <tr>
                      <td><strong>Bewaarplaats</strong></td>
                      <td>
                        <div class="value">Boerenbond (eigenaar)</div>
                        <div class="value">KADOC - KU Leuven (bewaarinstelling)</div>
                      </td>
                    </tr>
                    <tr>
                      <td><strong>Rechtenstatus</strong></td>
                      <td>
                        <div class="value">
                          <a href="http://rightsstatements.org/vocab/InC-NC/1.0/"><img class="right-img" src="https://rightsstatements.org/files/buttons/InC-NC.white.svg"></a>                          
                          <br>
                          Voorwaarden voor hergebruik worden bepaald door de rechthebbenden. Gebruik <a href="https://cagnet.be/page/aanvraag?aanvraag=1&amp;id=<?= $item->id();?>">het aanvraagformulier</a> voor meer informatie. 
                        </div>
                      </td>
                    </tr>
                  <?php endif;?>
                  <?php if($type == 'Film'):
                    $copies = $item->value('dcterms:isReferencedBy',array('all'=>true));
                    if($copies):
                    ?>
                    <tr><td><strong>Filmkopies</strong></td>
                      <td>
                          <?php foreach($copies as $copy):?>
                            <?php $text = $copy;?>
                            <?php $querycopy = 'property[0][joiner]=and&property[0][property]=27&property[0][type]=eq&property[0][text]='.$text.'&resource_class_id[]=&resource_template_id[]=13&item_set_id[]=&site_id=';?>
                            <?php parse_str($querycopy,$querycopy);?>
                            <?php $filmkopie = $this->api()->searchOne('items',$querycopy);?>
                            <?php $filmkopie = $filmkopie->getContent();?>
                            <?php if($filmkopie):?>
                              <div style="margin-bottom:0.7rem;">
                                <a class="copy_button untoggled" href="#<?php echo $copy; ?>"><?php echo $filmkopie->value('dcterms:title');?></a>
                                  <span style="display:none;"> <!-- content text must be in a wrapper if it's directly in a grid__item -->
                                      <table id="<?php echo $copy;?>" class="" style="border-left:1px solid #006b65;padding-left: 1rem;margin:10px 0 10px 0.8rem ;">
                                          <tbody>
                                            <?php echo $filmkopie->displayValues();?>
                                          </tbody>
                                      </table>
                                  </span>
                              </div>
                              <?php endif;?>
                            <?php endforeach;?>
                      </td>
                    </tr>

                    <?php endif;?>
                  <?php endif; ?>
                </tbody>
            </table>
        </span>
        <?php if($type == "Beeld"):?>
          <br />
          <ul class="list--arrow">
            <li>Klik <a class="hr" href="/page/aanvraag?aanvraag=1&id=<?php echo$item->value('dcterms:identifier');?>">hier</a> om een hogeresolutieversie van bovenstaande afbeelding aan te vragen.</li>
            <li>Klik <a href="/page/copyright-gebruiksvoorwaarden">hier</a> voor de voorwaarden voor beeldaanvragen.</li>
          </ul>
        <?php endif?>
        <?php if($type == "Ledenblad"):?>
          <br />
          <ul class="list--arrow">
            <li>Klik <a class="hr" href="/page/aanvraag?aanvraag=1&id=<?php echo$item->id();?>">hier</a> om een hogeresolutieversie van bovenstaande afbeelding aan te vragen.</li>
            <li>Klik <a href="/page/copyright-gebruiksvoorwaarden">hier</a> voor de voorwaarden voor deze aanvragen.</li>
          </ul>
        <?php endif?>
        <?php if($type == "Film"):?>
          <br />
          <ul class="list--arrow">
            <li>Klik <a class="hr" href="/page/copyright-gebruiksvoorwaarden-film">hier</a> voor copyright en gebruiksvoorwaarden filmdatabank.</li>
          </ul>
        <?php endif?>
  </div>
  <?php if ($searchReferer && $type != "Verhaal"): ?>
  <div class="container" style="">
    <a href="<?= htmlspecialchars($searchReferer) ?>" class=""><i class="icon icon--lrg icon--search js-search-icon"></i>Terug naar zoekresultaten</a>
  </div>
<?php endif; ?>
</div>
<?php endif;?>



<?php
$translate = $this->plugin('translate');

if($type != 'Nieuws' && $type != 'Agendapunt'):
  if($type == "Collectie"):
    $provincie = $item->value('dcterms:coverage');
    parse_str("property[0][joiner]=and&property[0][property]=14&property[0][type]=eq&property[0][text]=".$provincie."&resource_class_id[]=&resource_template_id[]=7&item_set_id[]=&site_id=&submit=Zoeken", $query);
  elseif($type == "Beeld"):
    parse_str("property[0][joiner]=and&property[0][property]=3&property[0][type]=eq&property[0][text]=&resource_class_id[]=&resource_template_id[]=6&item_set_id[]=&site_id=&submit=Zoeken", $query);
    $query['property'][0]['text'] = $item->value('dcterms:subject');
  elseif($type == "Film"):
      parse_str("property[0][joiner]=and&property[0][property]=3&property[0][type]=in&property[0][text]=&resource_class_id[]=&resource_template_id[]=10&item_set_id[]=&site_id=&submit=Zoeken", $query);
      $subject = explode(';',$item->value('dcterms:subject'));
      $query['property'][0]['text'] = $subject[0];
  elseif($type == "Filmkopie"):
      parse_str("property[0][joiner]=and&property[0][property]=3&property[0][type]=eq&property[0][text]=&resource_class_id[]=&resource_template_id[]=13&item_set_id[]=&site_id=&submit=Zoeken", $query);
      $query['property'][0]['text'] = $item->value('dcterms:subject');
  elseif($type == "Ledenblad"):
      parse_str("resource_template_id[]=37&item_set_id[]=&site_id=&submit=Zoeken", $query);
      //$query['property'][0]['text'] = $item->value('dcterms:subject');
  endif;

  $originalQuery = $query;

  $query['site_id'] = $site->id();
  $query['limit'] = 500;
  $query['sort_by'] = 'created';
  $query['sort_order'] = 'desc';

  $items = $this->api()->search('items',$query);
  $items = $items->getContent();

  //pick random items
  if(sizeof($items) > 1):
    $count = sizeof($items) < 3 ? sizeof($items) : 3;
    $keys = array_rand($items,$count);
    $resources = array();
    foreach($keys as $key):
      $resources[] = $items[$key];
    endforeach;
  //this means that only the current or no item was found
  elseif(sizeof($items) <= 1):
    $resources = array();
  endif;
  ?>
  <?php if($resources):?>
    <div class="section section--default">

      <div class="container">
        <?php if($type == "Collectie"):?>
          <h2>Collecties in de buurt</h2>
        <?php elseif($type == "Beeld"): ?>
          <h2>Andere interessante beelden</h2>
        <?php elseif($type == "Film"): ?>
          <h2>Andere interessante films</h2>
        <?php elseif($type == "Filmkopie"): ?>
          <h2>Andere interessante filmkopies</h2>
          <?php elseif($type == "Ledenblad"): ?>
            <h2>Andere ledenbladen</h2>  
        <?php endif;?>

        <div class="grid grid--3-col@med spacer--xsm">
          <?php foreach($resources as $resource):?>
            <?php            
              if($type == 'Ledenblad'):
                $title = $resource->displayTitle();
                $title = explode(", ",$title);
                $date = $title[1];
                $title = explode(":",$title[2]);
                $nr = $title[0];
                $title = $title[1];
                $title = trim($title).", ".$date.", ".$nr;
              else:
                $title = $resource->displayTitle();
              endif;    
            ?>
          <div class="grid__item">
            <div class="card card--gray card--clickable card--link card-variant2">
               <?php $media = $resource->primaryMedia(); ?>
               <?php if ($media): ?>
                 <?php
                   $url = str_replace('http:', '', $media->thumbnailUrl('medium'));
                 ?>
                 <div class="card__img card__img_3"
                   style="background:url(<?php echo $url;?>) no-repeat center 20%;background-size: cover;"
                 ></div>
               <?php endif; ?>

               <div class="card__body panel panel--light">
                   <h2 class="heading--3 card__title"><?php echo $resource->link($title); ?></h2>
                   <?php if ($description = $resource->displayDescription()): ?>
                      <?php $description = strip_tags($description);?>
                       <p class="description">
                           <?php echo strlen($description) > 200 ? substr($description,0,200).'..' : $description; ?>
                       </p>
                   <?php endif; ?>
                   <?php if($type == 'Ledenblad'):?>
                      <div class="link link--ext card__link"><a href="<?php echo "/s/test/item/".$resource->id();?>">Meer info</a></div>
                   <?php else:?> 
                      <div class="link link--ext card__link"><a href="<?php echo $resource->url();?>">Meer info</a></div>
                   <?php endif;?>
                  </div>
            </div>
          </div>
          <?php endforeach; ?>
        </div>
        <div class="text--center u-mt-med">
          <?php if($type == "Collectie"):?>
            <a href="/collecties?q=" class="btn btn--ext">
              Bekijk alle collecties
            </a>
          <?php elseif($type == "Beeld"): ?>
            <a href="/beeldbank?q=&limit[dcterms:subject][0]=<?php echo $item->value('dcterms:subject');?>" class="btn btn--ext">
              Bekijk alle beelden
            </a>
          <?php endif;?>
        </div>
      </div>
    </div>
  <?php endif; ?>
<?php endif; ?>

<script>
  $(document).ready(function(){
  if(typeof $.fn.slick != 'undefined'){  
      $('.slider-for').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: false,
        fade: true,
        centerMode: true,
        asNavFor: '.slider-nav'
      });
      $('.slider-nav').slick({
        slidesToShow: 10,
        slidesToScroll: 1,
        asNavFor: '.slider-for',
        focusOnSelect: true
      });
      $('.slick-embed').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: true,
        fade: true,
        centerMode: true
      });
    }
    $('.beeld').on('contextmenu', 'img', function(e){
      return false;
    });

    $(".copy_button").click(function(e){
        e.preventDefault();
        $(this).next("span").fadeToggle("slow");
        $(this).toggleClass('toggled untoggled');
    });
  });
</script>
