<div class="section section--default">
    <div class="container">
        <?php if($attachments):
            $media = $attachments[0]->media();
            $url = $media->thumbnailUrl('large');
            $url = str_replace('http:', '', $url);
          ?>
          <img src="<?php echo $url;?>">
          <figcaption><?php echo $attachments[0]->caption();?></figcaption>
        <?php endif;?>
    </div>
</div>
