version: '2'

services:

  omeka-s:
    build: ./
    ports:
      - "9001:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/:/var/www/html/themes/
      - ./files/:/var/www/html/files/
      - ./config/:/var/www/html/config/
      - ./imagemagick-policy.xml:/var/www/html/imagemagick-policy.xml
      - ./htaccess:/var/www/html/.htaccess
    restart: always
