version: '2'

services:

  omeka-s:
    build: ./
    ports:
      - "9016:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/:/var/www/html/themes/
      - ./files/:/var/www/html/files/
      - ./config/:/var/www/html/config/
      - ./htaccess:/var/www/html/.htaccess
      - ./OEmbed.php:/var/www/html/application/src/Media/Ingester/OEmbed.php
      - ./imagemagick-policy.xml:/var/www/html/imagemagick-policy.xml
    restart: "no"
