services:

  omeka-s:
    build: ./
    networks:
      - my-network
    ports:
      - "9016:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/:/var/www/html/themes/
      - ./files/:/var/www/html/files/
      - ./config/:/var/www/html/config/
      - ./htaccess:/var/www/html/.htaccess
    restart: "no"

networks:
  my-network:
    external:
      name: dev-network    
