<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response)) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchPage->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchPage->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayButton = $displayFacetButton ? $searchPage->subSetting('facet', 'display_button', 'above') : 'none';

$facetActive = $plugins->get('facetActive');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');
$facetSelectRange = $plugins->get('facetSelectRange');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchPage->setting('facet', []);
?>

<div class="grid__12 grid__4@med">
   <div class="panel panel--light">
    <h2>Filter <?php echo lcfirst($searchPage->name());?></h2>
    <?php //echo $this->searchForm($searchPage, null,true); ?>
        <?php if($query->getQuery()):?>
            <div class="current-query">
                Zoekopdracht: <a title="verwijder zoekopdracht" href="<?= parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH).'?q=' ?>"><?= htmlspecialchars($query->getQuery());?> <span class="icon icon--clear"></span></a></button>
            </div>
            <hr>
        <?php endif;?>
        
        <h4 style="margin-bottom: 0.5rem;">Tekstueel zoeken</h4>
        <div class="spacer">
        <?php if($searchPage->name() == "Ledenbladen"):?>    
            <?php echo $this->searchForm(); ?>
            <button class="add_field_button" type="button"><i class='fas fa-plus'></i> Een extra veld toevoegen</button>
        <?php else:?>    
           <form>            
            <div class="form__item">
                    <input type="text" name="q" class="form__text" value="<?= htmlspecialchars($query->getQuery());?>">
            </div>
            <div class="form__actions">
                    <button type="submit" class="btn form__btn">zoeken <span class="icon icon--search"></span></button>
            </div>
           </form>
        <?php endif; ?>
        </div>    

        <hr>          
    <?php if(!empty($searchPage->name('facet', 'facets'))):?>    

        <h3><?= $translate('Filters') ?></h3>

        <?php if($searchPage->name() == "Beeldbank"):?>  
        <form method="GET" id="psl-search-form">
            <div id="psl-search-form-date">
              <?php 
                $dates = $query->getDateRangeFilters();
                //var_dump($dates);
                $to = date("Y");$from = '1500';
                if($dates):
                  $from = $dates["dcterms_temporal_drm"][0]["from"];                  
                  $to = $dates["dcterms_temporal_drm"][0]["to"];
                endif;         
                if(!$from){$from = "1500";}       
                if(!$to){$from = date("Y");}   
              ?>
              <label><?php echo $this->translate('Periode'); ?> 
              <span class="currentDate">
                <?php if($from && $to):?>
                  <?php echo $from." - ".$to;?>
                <?php endif;?>  
              </span>
              </label>
              <?php //echo $this->formCollection($form->get('date'), false); ?>
              <div class="field" style="display: none;">
              <div class="field-meta">
                  <label for="dcterms_temporal_drm[from]">From year</label>            </div>
              <div class="inputs">                
                  <input type="text" name="dcterms_temporal_drm[from]" placeholder="YYYY" value="<?php echo $from;?>">    </div>
              </div>
              <div class="field" style="display: none;">
              <div class="field-meta">
                  <label for="dcterms_temporal_drm[to]">To year</label>            </div>
              <div class="inputs">
                  <input type="text" name="dcterms_temporal_drm[to]" placeholder="YYYY" value="<?php echo $to;?>">    </div>
              </div>
              <div id="psl-search-form-date-slider"></div>
              <div id="psl-search-form-date-graduations">
                  <div><?php echo $this->translate('1500'); ?></div>
                  
                  <div><?php echo $this->translate('1750'); ?></div>
                  <div><?php echo $this->translate('2023'); ?></div>
              </div>
            </div>  
            <div class="psl-tab-submit"><input type="submit" value="OK"/></div>      
          </form>
        <?php endif;?>            
        <div class="spacer">    
            <?php if ($displayActive && count($activeFacets)): ?>
                <h4><?= $translate('Actieve filters') ?></h4>
            
                <div class="search-facets-active">
                    <?php foreach ($activeFacets as $name => $facetValues) foreach ($facetValues as $facetKey => $facetValue): ?>
                    <div><?= $facetActive($name, ['value' => $facetValue, 'count' => null, 'key' => $facetKey], $options) ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <form id="form-facets">

                <?php if ($displayFacetButton): ?>
                <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
                <?php endif; ?>

                <?php if ($displayFacetButton && ($displayButton === 'above' || $displayButton === 'both')): ?>
                <div class="apply-facets apply-facets-top" style="margin-bottom:1rem;">
                    <button id="apply-facets" class="btn form__btn active" type="submit"><?= $translate('Filters toepassen') ?></button>
                </div>
                <?php endif; ?>

                <?php if (empty($facets) && empty($activeFacets)): ?>
                <p><?= $translate('No facets.') ?></p>
                <?php else: ?>
                <div class="search-facets-list">
                    <?php foreach ($facets as $name => $facetValues): ?>
                    <?php $facetType = empty($options['facets'][$name]['type']) ? 'Checkbox' : $options['facets'][$name]['type']; ?>
                    <h4><?= $translate($facetLabel($name)) ?></h4>
                    <?php
                        if($facetLabel($name) == 'Onderwerp' || $facetLabel($name) == 'Status'):
                        $class="no-caps";
                        else:
                        $class="";
                        endif;
                    ?>
                    <div class="form__group <?php echo $class;?>">
                        
                        <?php if ($facetType === 'Select'): ?>
                        <?= $facetSelect($name, $facetValues, $options) ?>
                        <?php elseif ($facetType === 'SelectRange'): ?>
                        <?= $facetSelectRange($name, $facetValues, $options) ?>
                        <?php else: ?>
                        <?= $facetElements($name, $facetValues, $options) ?>
                        <?php endif; ?>
                    </div>
                    <?php endforeach; ?>
                </div>
                <?php endif; ?>

                <?php if ($displayFacetButton && ($displayButton === 'below' || $displayButton === 'both')): ?>
                <div class="apply-facets apply-facets-bottom" style="margin-top:1rem;">
                    <button id="apply-facets" class="btn form__btn" type="submit"><?= $translate('Filters toepassen') ?></button>
                </div>
                <?php endif; ?>
            </form>
        </div>
    <?php endif;?>
</div>
</div>



