<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Search\Query $query
 * @var \Search\Response $response
 * @var array $sortOptions
 * @var array $facets
 * @var bool $isPartial
 */

$plugins = $this->getHelperPluginManager();
$api = $plugins->get('api');
$partial = $plugins->get('partial');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$translatePlural = $plugins->get('translatePlural');

$vars = $this->vars();

// Used in case of a redirect of item-set/show to search, when used like item/browse.
$itemSetId = $this->params()->fromRoute('item-set-id');
// TODO Use site item set ?
/** @var \Omeka\Api\Representation\ItemSetRepresentation $itemSet */
$itemSet = $itemSetId ? $api->searchOne('item_sets', ['id' => $itemSetId])->getContent() : null;

$isPartial = $skipFormAction = !empty($skipFormAction);

$documentCount = isset($response) ? $response->getTotalResults() : 0;
if ($documentCount):
    $itemSetsCount = $response->getResourceTotalResults('item_sets');
    $itemsCount = $response->getResourceTotalResults('items');
    $displayParts = $searchConfig->setting('display', []);
    $displayPartsHeader = array_filter($displayParts, function ($v) { return in_array($v, ['header', 'both']); });
    $displayPartsFooter = array_filter($displayParts, function ($v) { return in_array($v, ['footer', 'both']); });
endif;

$this->htmlElement('body')->appendAttribute('class', 'search-page resource browse');
$this->headScript()->appendFile($this->assetUrl('jquery-ui.min.js', 'jQueryUI'));
$this->headLink()->appendStylesheet($this->assetUrl('jquery-ui.min.css', 'jQueryUI'));
$this->headLink()->appendStylesheet($this->assetUrl('css/search.css', 'Search'));
$this->headScript()->appendFile($this->assetUrl('js/search.js', 'Search'));
?>
<!-- intro + image -->
<div class="section section--lrg section--light">
   <div class="container">
      <?php 
       $page = $searchPage;
      ?>

       <!-- breadcrumbs -->
       <div class="breadcrumb spacer">
           <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
               <a href="/" itemprop="url" class="breadcrumb__item"><span itemprop="title">Home</span></a>
           </span>
           <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
              <?php if(htmlspecialchars($query->getQuery())):?>
                <span itemprop="title"><a href="<?= parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH).'?q=' ?>"><?php echo $page->name();?></a></span></span>
                <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
                <span itemprop="title"><?= htmlspecialchars($query->getQuery())?></span></span>
              <?php else:?>
               <span itemprop="title"><?php echo $page->name();?></span>
              <?php endif;?>
           </span>
       </div>
       <h1 class="spacer">
         <?php echo $page->name()." (".$response->getTotalResults().")";?>
       </h1>

        <?php
        $intro = array(
          "Verhalen" => "De verhalen laten je in woord en beeld de geschiedenis en het erfgoed van landbouw, voeding en landelijke leven vanaf 1750 ontdekken. Zes keer per jaar verschijnt een nieuw verhaal.",
          "Projecten" => "CAG werkt als initiatiefnemer, uitvoerder en deelnemer aan tal van projecten in het themaveld landbouw, voeding en landelijk leven. Sommige projecten hebben een onderzoekskarakter, andere zijn gericht op een breed publiek. Zowel roerend als immaterieel erfgoed komen aan bod.",
          "Beeldbank" => "De beeldbank van CAG bevat meer dan 12.000 digitale reproducties van agrarisch erfgoed (objecten, foto’s, prenten, boeken ...). Dankzij die rijkdom neemt de beeldbank je mee naar het virtuele land van 1750 tot vandaag.",
          "Collecties" => "Ben je op zoek naar een publiek toegankelijke collectie met erfgoed van landbouw, voeding en landelijk leven? Hier vind je een overzicht.",
          "Cinema Rural Filmdatabank" => "De Cinema Rural Filmdatabank biedt een overzicht met uitgebreide inhoudelijke en materiële beschrijvingen van het bewegend beeldmateriaal van landbouw, voeding en landelijk leven dat wordt bewaard in Belgische collecties."
          );
        ?>
        <?php if(isset($intro[$page->name()])):?>
         <div class="text--lead spacer">
           <?php echo $intro[$page->name()];?>
         </div>
        <?php endif;?>
   </div>
</div>

<div class="section section--default">
  <div class="container">
    <?php if (isset($response)): ?>
        <?php if ($response->getTotalResults() > 0): ?>
           <?php
               echo $this->partial('search/results-header', [
                'site' => $site,
                'searchConfig' => $searchConfig,
                // Kept for compatibility with old themes.
                'searchPage' => $searchConfig,
                'query' => $query,
                'response' => $response,
                'itemSet' => $itemSet,
                'resultPart' => 'header',
                'documentCount' => $documentCount,
               ]);
           ?>
       <?php endif; ?>
    <?php endif; ?>
    <div class="grid">

     <!-- search filter -->
     
     <?php if($page->name() != 'Verhalen'):?>
      <?= $partial('search/facets', [
        'site' => $site,
        'searchPage' => $searchPage,
        'query' => $query,
        'response' => $response,
        'itemSet' => $itemSet,
    ]) ?>
         <?php endif;?>


     <!-- filter results -->
     <?php if (isset($response)): ?>
          <?php if ($response->getTotalResults() > 0): ?>

              <?php $itemSetsCount = $response->getResourceTotalResults('item_sets'); ?>
              <?php
              echo $this->partial('search/resource-list', [
                  'title' => sprintf($this->translatePlural('%s item set', '%s item sets', $itemSetsCount), $itemSetsCount),
                  'response' => $response,
                  'resourceName' => 'item_sets',
                  'site' => $site
              ]);
              ?>

              <?php $itemsCount = $response->getResourceTotalResults('items'); ?>
              <?php
              echo $this->partial('search/resource-list', [
                  'title' => sprintf($this->translatePlural('%s item', '%s items', $itemsCount), $itemsCount),
                  'response' => $response,
                  'resourceName' => 'items',
                  'site' => $site,
                  'pagename' => $page->name()
              ]);
              ?>


              <?php echo $this->pagination(); ?>
          <?php else: ?>
              <div class="noresults"><?php echo $translate('Your query returned no results'); ?></div>
          <?php endif; ?>
      <?php endif; ?>
      <?php if (empty($isPartial)): ?>

      <?php endif; ?>
      </div>
  </div>
</div>
<?php 
                $dates = $query->getDateRangeFilters();
                //var_dump($dates);
                $to = date("Y");$from = '1500';
                if($dates):
                  $from = $dates["dcterms_temporal_drm"][0]["from"];                  
                  $to = $dates["dcterms_temporal_drm"][0]["to"];
                endif;         
                if(!$from){$from = "1500";}       
                if(!$to){$from = date("Y");}   
              ?>
<script>
    $(document).ready(function(){
        $( ".more-link a" ).click(function(e) {
            e.preventDefault();
            $(this).parent().hide();
            $(this).parent().next( "div" ).show();
        });
        $( ".less-link a" ).click(function(e) {
            e.preventDefault();
            $(this).parent().parent().hide();
            $(this).parent().parent().prev( ".more-link" ).show();
        });
    });
</script>
<script>
    $(document).ready(function() {
    var dateFrom = $('#psl-search-form input[name="dcterms_temporal_drm[from]"]');
    var dateTo = $('#psl-search-form input[name="dcterms_temporal_drm[to]"]');
    var dateMin =1500;
    var dateMax = 2023;
    var currentDate = '';
    console.log(dateFrom.val() + "," + dateTo.val());

    $('#psl-search-form-date-slider').slider({
        range: true,
        min: dateMin,
        max: dateMax,        
        step: 10,
       
        //values: [dateFrom.val() || dateMin, dateTo.val() || dateMax],
        values: [<?php echo $from;?>, <?php echo $to;?>],
        change: function(event, ui) {
            var from = ui.values[0] > dateMin ? ui.values[0] : '';
            var to = ui.values[1] < dateMax ? ui.values[1] : '';
            if (from != dateFrom.val()) {
                dateFrom.val(from).change();
            }
            if (to != dateTo.val()) {
                dateTo.val(to).change();
            }

            var fromv = from;
            if(from == 0){
              fromv = 1500;
            }
            var tov = to;
            if(to == ''){
              tov = 2023;
            }
            $('.currentDate').text((fromv) + ' - ' + tov);
        }
    });

    dateFrom.parents('.field').hide();
    dateTo.parents('.field').hide();
  });
</script>
