<div class="section section--default">
    <div class="container">
        <?php if($block->dataValue('reverse')):?>
        <div class="grid grid--reverse grid--2-col@med">
        <?php else:?>
        <div class="grid grid--2-col@med">
        <?php endif;?>
        <div class="grid__item">
            <span> <!-- content text must be in a wrapper if it's directly in a grid__item -->
                <h2><?php echo $block->dataValue('title');?></h2>
                <?php echo $block->dataValue('text');?>
                <?php if($block->dataValue('link')):?>
                    <a class="link link--ext spacer" href="<?php echo $block->dataValue('link');?>"><?php echo $block->dataValue('label');?></a>
                <?php endif;?>
            </span>
        </div>
        <div class="grid__item">
            <?php if($attachments):
              $media = $attachments[0]->media();
              if($block->dataValue('itemurl')):
                $itemUrl = $media->item()->url();?>
                <a href="<?php echo $itemUrl;?>"><?php echo $this->thumbnail($media, 'large',array('class' => 'u-display-block'));?></a>
              <?php else:
                echo $this->thumbnail($media, 'large');
              endif;  
              ?>
            <figcaption><?php echo $attachments[0]->caption();?></figcaption>
          <?php endif;?>
        </div>

        </div>
    </div>
</div>
