<div class="section section--default">
    <div class="container">
        <?php if($block->dataValue('reverse')):?>
        <div class="grid grid--reverse grid--2-col@med">
        <?php else:?>
        <div class="grid grid--2-col@med">
        <?php endif;?>
        <div class="grid__item">
            <span> <!-- content text must be in a wrapper if it's directly in a grid__item -->
                <h2><?php echo $block->dataValue('title');?></h2>
                <?php echo $block->dataValue('text');?>
                <?php if($block->dataValue('link')):?>
                    <a class="link link--ext spacer" href="<?php echo $block->dataValue('link');?>"><?php echo $block->dataValue('label');?></a>
                <?php endif;?>
            </span>
        </div>
        <div class="grid__item">
            <?php if($attachments):
              $media = $attachments[0]->media();
              $url = $media->thumbnailUrl('large');
              $url = str_replace('http:', '', $url);
              if($media):
                if($block->dataValue('itemurl')):
                  $itemUrl = $media->item()->url();
                  $itemUrl = str_replace('http:', '', $itemUrl);
                  ?>
                  <a href="<?php echo $itemUrl;?>"><img src="<?php echo $url;?>"></a>
                <?php else:?>
                  <img src="<?php echo $url;?>">
                <?php endif;?>
              <?php endif;?>
            <figcaption><?php echo $attachments[0]->caption();?></figcaption>
          <?php endif;?>
        </div>

        </div>
    </div>
</div>
