<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();

if($template):
  $type = $template->label();
else:
  $type = "";
endif;

$thumb = $item->primaryMedia();
?>

<!-- beeldbank: image / table -->
<div class="section section--default">
  <div class="container">
    <div class="breadcrumb spacer">
        <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
            <a href="<?php echo $site->url();?>" itemprop="url" class="breadcrumb__item"><span itemprop="title">Home</span></a>
        </span>
        <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
          <?php if($type == "News"):?>
            <a href="/s/en/news?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">News</span></a>
          <?php elseif($type == "Event"):?>
            <a href="/s/en/event?q=" itemprop="url" class="breadcrumb__item"><span itemprop="title">Event</span></a>
          <?php endif;?>
        </span>
        <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
            <span itemprop="title"><?php echo $item->displayTitle();?></span>
        </span>
    </div>
    <h1><?php echo $this->pageTitle($item->displayTitle(), 2); ?></h1>
    <?php if($item->value('dcterms:date') && ($type == 'Nieuws' || $type == 'Agendapunt' || $type == 'News')):?>
        <?php
          $date = $item->value('dcterms:date');
          //echo $date;
          $output = DateTime::createFromFormat('Ymd', $date);
          if(!$output){
              $output = DateTime::createFromFormat('Y-m-d', $date);
          }
          $output = $output->format('d-m-Y');
        ?>
        <p class="datering"><?php echo $output;?></p>
    <?php endif;?>
  </div>
</div>

<div class="section section--default">
  <div class="container">
    <div class="grid grid--2-col@med">
      <div class="grid__item">
        <?php echo $item->displayDescription(); ?>
      </div>
      <div class="grid__item">
        <?php if(sizeof($itemMedia) > 1):?>
          <div class="slider-for">
            <?php foreach($itemMedia as $media):?>
              <div class="beeld">
                <?php
                  $render =  $media->render();
                  $render = str_replace('http:', '', $render);
                  echo $render;
                  //$url = str_replace('http:', '', $media->thumbnailUrl('large'));
                ?>
                <!--<img src="<?php echo $url;?>">-->
              </div>
            <?php endforeach;?>
          </div>
          <div class="slider-nav" role="toolbar">
            <?php foreach($itemMedia as $media):?>
              <div class="beeld-nav">
                <?php
                  $url = str_replace('http:', '', $media->thumbnailUrl('square'));
                ?>
                <img src="<?php echo $url;?>">
              </div>
            <?php endforeach;?>
          </div>
        <?php else: ?>
          <div class="beeld">
            <?php
              //$url = str_replace('http:', '', $itemMedia[0]->thumbnailUrl('large'));
              $render =  $itemMedia[0]->render();
              $render = str_replace('http:', '', $render);
              echo $render;
            ?>
            <!--<img src="<?php echo $url;?>">-->
          </div>
        <?php endif;?>
      </div>
    </div>

    <?php $this->trigger('view.show.after'); ?>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: false,
      fade: true,
      centerMode: true,
      asNavFor: '.slider-nav'
    });
    $('.slider-nav').slick({
      slidesToShow: 10,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      focusOnSelect: true
    });

    $('.beeld').on('contextmenu', 'img', function(e){
      return false;
    });
  });
</script>
