<!-- overview blocks -->
<?php if($attachments):?>
<div class="section section--default">
    <div class="container">
        <div class="grid grid--2-col@sml grid--3-col@med">
          <?php for($i = 1; $i <= 3; $i++){ ?>
            <div class="grid__item">
                <div class="card card--clickable card--link card--variant">
                  <a href="<?php echo $block->page()->site()->url().$block->dataValue('link'.$i);?>">
                    <div class="card__img">
                      <?php
                        if($attachments[$i-1]):
                          $media = $attachments[$i-1]->media();
                          $url = '';
                          if($media):
                            if($media->mediaType() == 'text/html'):
                              $url = $media->originalUrl();
                            else:
                              $url = $media->thumbnailUrl('medium');
                            endif;
                          endif;
                          ?>
                          <img src="<?php echo $url;?>">
                          <?php
                        endif;
                      ?>

                    </div>
                    <div class="card__body">
                        <!-- make whole card clickable -->
                        <h2 class="heading--3 card__title">
                            <a href="<?php echo $block->page()->site()->url().$block->dataValue('link'.$i);?>"><?php echo $block->dataValue('title'.$i);?></a>
                        </h2>
                        <?php echo $block->dataValue('text'.$i);?>
                        <?php if($block->dataValue('link'.$i) && $block->dataValue('linktext'.$i)):?>
                       <div class="link link--ext card__link"><a href="<?php echo $block->page()->site()->url().$block->dataValue('link'.$i);?>"><?php echo $block->dataValue('linktext'.$i);?></a></div>
                     <?php endif;?>
                    </div>
                  </a>
                </div>
            </div>
          <?php } ?>
        </div>
    </div>
</div>
<?php else:?>
  <p>
    Om dit blok te gebruiken moet je 3 afbeeldingen (attachments) selecteren.
  </p>
<?php endif;?>
