<div class="section section--default text-only">
    <div class="container">
        <h2 class="spacer">Zoeken in het landbouwpersrepertorium</h2>
          <div class="grid">
            <div class="grid__12 grid__8@med">
                <span> <!-- content text must be in a wrapper if it's directly in a grid__item -->
                  <p><strong>Tip</strong>: Gebruik het trefwoord &lsquo;CAG&rsquo; bij &lsquo;zoeken in de tekst&rsquo; om alle titels te zien.</p>
                  <p>
                  <script type="text/javascript">// <![CDATA[
                  function Search()
                            {

                              document.getElementById('search_form').action = 'http://www.odis.be/hercules/search2.php';
                              document.getElementById('search_form').submit();
                            };
                  // ]]></script>
                  </p>
                  <form id="search_form" method="get" target="_blank">
                  <table>
                  <tbody>
                  <tr>
                  <td><input id="searchMethod1" type="radio" name="searchMethod" value="simple" checked="checked" /><label for="searchMethod1">Zoeken op titel</label> &nbsp; <input id="searchMethod2" type="radio" name="searchMethod" value="full" /><label for="searchMethod2">Zoeken in de tekst</label></td>
                  </tr>
                  <tr>
                  <td><textarea id="search" onkeydown="if (event.keyCode == 13) {Search(); return false; }" name="search" rows="2" cols="50"></textarea></td>
                  </tr>
                  <tr>
                  <td><button onclick="Search();" type="button"><strong>Zoek</strong></button></td>
                  </tr>
                  </tbody>
                  </table>
                  <input type="hidden" name="controlid" value="263" /> <input type="hidden" name="entity" value="PUB" /></form>
                </span>
            </div>
        </div>
    </div>
</div>
