<!-- overview blocks -->
<?php if(sizeof($attachments) == 3 || sizeof($attachments) == 2):?>
<div class="section section--default column-block">

    <div class="container">
        <h2><?php echo $block->dataValue('title');?></h2>
        <div class="grid grid--<?php echo sizeof($attachments);?>-col@med spacer--xsm">
          <?php for($i = 1; $i <= sizeof($attachments); $i++){ ?>
            <div class="grid__item">
                <div class="card card--gray card--clickable card--link">
                  <a href="<?php echo $block->dataValue('link'.$i);?>">
                    <?php
                      $url='';
                      if($attachments[$i-1]):
                        $media = $attachments[$i-1]->media();
                        if($media):
                          if(sizeof($attachments) <= 2):
                            $url = $media->thumbnailUrl('large');
                            $url = str_replace('http:', '', $url);
                          else:
                            $url = $media->thumbnailUrl('medium');
                            $url = str_replace('http:', '', $url);
                          endif;
                        endif;
                      endif;
                    ?>
                    <div class="card__img card__img_<?php echo sizeof($attachments);?>"
                      style="background:url(<?php echo  $url;?>) no-repeat center 20%;background-color:#7fb5b2;background-size: cover;"
                      >
                    </div>
                    <div class="card__body panel panel--light">
                        <h2 class="heading--3 card__title spacer--xsm">
                            <a href="<?php echo $block->dataValue('link'.$i);?>"><?php echo $block->dataValue('title'.$i);?></a>
                        </h2>
                        <?php echo $block->dataValue('text'.$i);?>
                        <?php if($block->dataValue('link'.$i) && $block->dataValue('linktext'.$i)):?>
                        <div class="link link--ext card__link"><a href="<?php echo $block->dataValue('link'.$i);?>"><?php echo $block->dataValue('linktext'.$i);?></a></div>
                     <?php endif;?>
                    </div>
                  </a>
                </div>
            </div>
          <?php } ?>
        </div>
    </div>
</div>
<?php else:?>
  <p>
    Om dit blok te gebruiken moet je minstens 2 afbeeldingen (attachments) selecteren.
  </p>
<?php endif;?>
