<?php
$translate = $this->plugin('translate');
?>
<!-- pagination -->
<?php if ($totalCount): ?>
<div class="section section--default">
    <div class="container">
        <div class="text--center">
            <ul class="pagination">

                <?php if ($currentPage != 1): ?>
                <li class="pagination__item">
                    <a href="<?php echo $previousPageUrl;?>" class="pagination__prev"><span class="visuallyhidden">Vorige</span></a>
                </li>

                <li class="pagination__item">
                    <a href="<?php echo $previousPageUrl;?>" class="pagination__btn"><?php echo $currentPage-1; ?></a>
                </li>
                <?php endif; ?>

                <li class="pagination__item">
                    <a href="#" class="pagination__btn active"><?php echo $currentPage; ?></a>
                </li>

                <?php if ($currentPage < $pageCount): ?>
                  <li class="pagination__item">
                      <a href="<?php echo $nextPageUrl;?>" class="pagination__btn"><?php echo $currentPage+1; ?></a>
                  </li>

                  <li class="pagination__item">
                      <a href="<?php echo $nextPageUrl;?>" class="pagination__next"><span class="visuallyhidden">Volgende</span></a>
                  </li>
                <?php endif; ?>

            </ul>
        </div>
    </div>
</div>
<?php else: ?>
    <?php echo $translate('0 results'); ?>
<?php endif; ?>
