<div class="section section--default">
    <div class="container">
        <div class="panel panel--light panel--border panel--full">
            <span class="spacer panel__content">
                <h2><?php echo $block->dataValue('title');?></h2>
                <?php echo $block->dataValue('text');?>
            </span>
            <?php if($block->dataValue('link')):?>
              <div class="spacer">
                  <a href="<?php echo $block->dataValue('link');?>" class="btn spacer">Meer lezen</a>
              </div>
            <?php endif;?>
        </div>
    </div>
</div>
