<?php
$translate = $this->plugin('translate');
$biblio = array();
$niv = 'none';
if(isset($_GET['niv'])):
  $niv = $_GET['niv'];
endif;
if($niv == 'Werkinstrumenten'):
  $limit= 1;
elseif($niv == 'Synthesewerken'):

elseif($niv == 'Thematische studies'):

endif;

?>
<div class="section section--default">
  <div class="container">
    <div class="grid grid--<?php echo $block->dataValue('columns');?>-col@med spacer--xsm">
    <?php
      foreach ($this->resources as $resource):
          $biblio[$resource->value('dcterms:type')->value()][strip_tags($resource->value('dcterms:title')->value())] = $resource->value('dcterms:title')->value();
      endforeach;
      ksort($biblio,SORT_NATURAL);
    ?>
    <?php foreach($biblio as $title => $bibs): ?>
      <table class="table--striped">
        <thead>
            <tr>
                <?php $id = explode(" ", $title, 2); ?>
                <th colspan="2" id="<?php echo $id[0];?>"><?php echo $title;?></th>
            </tr>
        </thead>
        <tbody>
          <?php ksort($bibs);?>
          <?php foreach($bibs as $bib): ?>
            <tr>
                <td><?php echo $bib;?></td>
                <td class="text--right text--italic"></td>
            </tr>
          <?php endforeach;?>
        </tbody>
      </table>
    <?php endforeach;?>
    <?php
      /*echo "<pre>";
      var_dump($biblio);
      echo "</pre>";*/
    ?>
    </div>
  </div>
</div>
