<?php
$translate = $this->plugin('translate');
?>
<nav class="pagination" role="navigation" aria-label="pagination">
<?php if ($totalCount): ?>
    <?php if ($currentPage != 1): ?>
        <?php echo $this->hyperlink($translate('Vorige pagina'), $previousPageUrl, ['class' => 'pagination-previous', 'title' => $translate('Vorige pagina'), 'aria-label' => $translate('Vorige pagina')]); ?>
    <?php endif; ?>

    <form method="GET" action="">
        <?php echo $this->queryToHiddenInputs(['page']); ?>
        <input type="text" name="page" class="page-input-top" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>">
        <span class="page-count"><?php echo sprintf($translate('of %s'), $pageCount); ?></span>
    </form>

    <?php if ($currentPage < $pageCount): ?>
    <?php echo $this->hyperlink($translate('Volgende pagina'), $nextPageUrl, ['class' => 'pagination-next', 'title' => $translate('Volgende pagina'), 'aria-label' => $translate('Volgende pagina')]); ?>
    <?php endif; ?>

    <?php
    $from = $offset + 1;
    $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
    ?>
<?php else: ?>
    <?php echo $translate('0 results'); ?>
<?php endif; ?>
</nav>
