<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>

<?php
//catch entiteiten
foreach ($values as $term => $propertyData):
  //echo $term;
endforeach;
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php
    $dontshow = ['Titel','Description', 'Is Version Of', 'Relation', 'Language'];
    $entity_fields = ['Regisseur','Producent','Wetenschappelijk medewerker','Opdrachtgever','Sponsor','Medewerker','Eigenaar','Vervaardiger'];
    /*if(in_array($propertyData['property']->label(),$dontshow)):
      continue;
    endif;*/

    //echo $propertyData['property']->label();
    $template = $property->template()->label();

    if($property->isPrivate()):
      continue;
    endif;
    $propertyData = '';
    if(isset($values[$property->property()->term()])):
      $propertyData = $values[$property->property()->term()];
    else:
      continue;
    endif;
  ?>

  <tr>
      <td>
        <strong>
          <?php if ($property->alternateLabel()): ?>
          <?php echo $escape($property->alternateLabel()); ?>
          <?php else: ?>
          <?php echo $escape($translate($property->property()->label())); ?>
          <?php endif; ?>
          <?php if ('term' === $labelInfo): ?>
          <span class="field-term">(<?php echo $escape($property->term()); ?>)</span>
          <?php elseif ('vocab' === $labelInfo): ?>
          <span class="field-term">(<?php echo $escape($property->vocabulary()->label()); ?>)</span>
          <?php endif; ?>
        </strong>
      </td>

      <td>
        <?php foreach ($propertyData['values'] as $key=>$value): ?>
            <?php
            $valueType = $value->type();
            $class = ['value'];
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php
                  $text = $value->asHtml();                  

                  if($property->alternateLabel() == 'Bibliografische referentie' || $property->alternateLabel() == 'Entiteiten'):                
                    $string = preg_replace("/<a(.*?)>/", "<a$1 target=\"_blank\">", html_entity_decode($text));
                  elseif($property->alternateLabel() == 'Bewaarplaats'):
                    $string = $text;
                  else:
                    $string = preg_replace('@(https?://([-\w\.]+)+(:\d+)?(/([\w/_\.%-=#]*(\?\S+)?)?)?)@', '<a target="_blank" href="$1">$1</a>', $text);
                  endif;

                  //handle entiteiten
                  if(in_array($property->alternateLabel(),$entity_fields) && isset($values['dcterms:bibliographicCitation'])):
                    $text = $value->asHtml();
                    $orginal_text = $text;
                    //remove (...)
                    $text = explode('(',$text);
                    //trim whitespace
                    $text = trim($text[0]);
                    $string = $orginal_text;
                    //remove doubles
                    $entities = array();
                    foreach($values['dcterms:bibliographicCitation']['values'] as $entval):
                      $entities[$entval->asHtml()] = $entval;
                    endforeach;  
                    foreach($entities as $entval):
                      $ent = $entval->asHtml();
                      if (strpos($ent, $text) !== false) {
                        $links = explode('||', $ent);
                        //array_shift($array);
                        if($links[1] != ''):
                          $string .= ' <a target="_blank" href="'.$links[1].'"><span class="entity">Website</span></a>';
                        endif;  
                        if($links[2] != ''):
                          $string .= ' <a target="_blank" href="'.$links[2].'"><img style="height:18px;" src="/themes/default/asset/img/wiki.png" /></a>';
                        endif;  
                        if($links[3] != ''):
                          $string .= ' <a target="_blank" href="'.$links[3].'"><img style="height:18px;" src="/themes/default/asset/img/viaf.png" /></a>';
                        endif; 
                        if($links[4] != ''):
                          $string .= ' <a target="_blank" href="'.$links[4].'"><span class="entity">ULAN</span></a>';
                        endif; 
                        if($links[5] != ''):
                          $string .= ' <a target="_blank" href="'.$links[5].'"><span class="entity">RKDartists&</span></a>';
                        endif;
                        if($links[6] != ''):
                          $string .= ' <a target="_blank" href="'.$links[6].'"><span class="entity">Biografie</span></a>';
                        endif;
                      }
                    endforeach;
                  endif;

                  $rights = array(
                    'http://rightsstatements.org/vocab/InC-NC/1.0/' => array('link' => 'https://creativecommons.org/licenses/by/4.0/deed.nl','img' => 'https://rightsstatements.org/files/buttons/InC-NC.white.svg'),
                    'http://rightsstatements.org/vocab/InC-RUU/1.0/' => array('link' => 'https://creativecommons.org/licenses/by-nc/4.0/deed.nl','img' => 'https://rightsstatements.org/files/buttons/InC-RUU.white.svg'),
                    'http://rightsstatements.org/vocab/InC/1.0/' => array('link' => 'https://creativecommons.org/licenses/by-nc-nd/4.0/deed.nl','img' => 'https://rightsstatements.org/files/buttons/InC.white.svg'),
                    'http://rightsstatements.org/vocab/NKC/1.0/' => array('link' => 'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.nl','img' => 'https://rightsstatements.org/files/buttons/NKC.white.svg'),
                    'https://creativecommons.org/publicdomain/mark/1.0/' => array('link' => 'http://creativecommons.org/publicdomain/mark/1.0/deed.nl','img' => 'https://licensebuttons.net/p/mark/1.0/88x31.png'),

                  );

                  if(isset($rights[$text])):
                    if(isset($values['dcterms:rights'])):
                      $rightslink = $values['dcterms:rights']['values'][0]->asHtml();
                      $string = '<a href="'.$rightslink.'"><img class="right-img" src="'.$rights[$text]['img'].'" /></a>';
                    else:
                      $string = '<a href="'.$rights[$text]['link'].'"><img src="'.$rights[$text]['img'].'" /></a>';
                    endif;
                    if($template == 'Film'):
                      $string .= "<br />Neem contact op met de betreffende bewaarinstelling voor meer informatie over de rechtenstatus";
                    endif;
                    if($template == 'Beeld'):
                      $string .= '<br />Voorwaarden voor hergebruik worden bepaald door de rechthebbenden. Gebruik <a href="https://cagnet.be/page/aanvraag?aanvraag=1&id='.$value->resource()->id().'">het aanvraagformulier</a> voor meer informatie.';
                    endif;
                  endif;

                  if($property->alternateLabel() == 'Bewaarplaats'):
                    
                    $string = html_entity_decode($text);
                  endif;  

                  if($property->alternateLabel() == 'Bewaarplaats' && strpos($text, '||') !== false):
                    $brons = explode('||', $text);
                    if($brons[0]==''):
                      $string = $brons[1];
                    else:
                      $string = $brons[0];
                    endif;  
                  endif;  

                  if($property->alternateLabel() == 'Filmkopies'):
                    $query = 'property[0][joiner]=and&property[0][property]=27&property[0][type]=eq&property[0][text]='.$text.'&resource_class_id[]=&resource_template_id[]=13&item_set_id[]=&site_id=';
                    parse_str($query,$query);

                    $filmkopie = $items = $this->api()->searchOne('items',$query);
                    $filmkopie = $filmkopie->getContent();
                    if($filmkopie):
                      $string = '<a href="#'.$text.'">'.$filmkopie->displayTitle().'</a>';
                    else:
                      $string = "";
                    endif;
                  endif;

                  /*if($property->alternateLabel() == 'Medewerker' || $property->alternateLabel() == 'Onderwerp' ):
                    $text = str_replace(';','<br />',$text);
                    $string = $text;
                  endif;*/

                  if($property->alternateLabel() == 'Meer informatie'):
                    if (strpos($text,'wiki') !== false):                   
                      $string = '<a target="_blank" href="'.$text.'">Wikipedia <img style="height:18px;" src="/themes/default/asset/img/wiki.png" /></a>';
                    elseif (strpos($text,'viaf') !== false):   
                      $string = '<a target="_blank" href="'.$text.'">VIAF <img style="height:18px;" src="/themes/default/asset/img/viaf.png" /></a>';
                    elseif (strpos($text,'odis') !== false):   
                      $string = '<a target="_blank" href="'.$text.'">ODIS</a>';
                    elseif (strpos($text,'udal') !== false):   
                      $string = '<a target="_blank" href="'.$text.'">UDAL</a>'; 
                    elseif (strpos($text,'rkd.nl') !== false):   
                      $string = '<a target="_blank" href="'.$text.'">RKDartists&</a>';         
                    else:
                      $string = '<a target="_blank" href="'.$text.'">'.$text.'</a>';
                    endif; 
                  endif;

                  if($property->alternateLabel() == 'Beschikbaarheid' && $string == 'not online accessible to public'):
                    $string = "niet online raadpleegbaar";
                  endif;

                  if($property->alternateLabel() == 'Film'):
                    $text = str_replace('Filmcopy.','',$text);
                    $query = 'property[0][joiner]=and&property[0][property]=35&property[0][type]=in&property[0][text]='.$text.'&resource_class_id[]=&resource_template_id[]=10&item_set_id[]=&site_id=';
                    parse_str($query,$query);

                    $filmkopie = $items = $this->api()->searchOne('items',$query);
                    $filmkopie = $filmkopie->getContent();
                    if($filmkopie):
                      $string = $filmkopie->link($filmkopie->displayTitle());
                    else:
                      $string = "";
                    endif;
                  endif;

                  if($property->alternateLabel() == 'Genre'):
                    $string = '<a href="/films?q=&limit%5Bdcterms:type%5D%5B0%5D='.$text.'">'.$text.'</a>';
                  endif;

                  if($property->alternateLabel() == 'Onderwerp'):
                    $searchpages = array(
                      'Film' => 'films',
                      'Beeld' => 'beeldbank',
                      'Collectie' => 'collecties',
                      'Filmkopie' => 'filmkopies'
                    );
                    $template;
                    $string = '<a href="/'.$searchpages[$template].'?q=&limit%5Bdcterms:subject%5D%5B0%5D='.$text.'">'.$text.'</a>';
                  endif;

                  if($property->alternateLabel() == 'Plaats van vervaardiging'):
                    $codes = array(
                      'GB' => 'Verenigd Koninkrijk',
                      'UK' => 'Verenigd Koninkrijk',
                      'NL' => 'Nederland',
                      'IT' => 'Italië',
                      'SZ' => 'Zwitserland',
                      'FR' => 'Frankrijk',
                      'CN' => 'Canada',
                      'BE' => 'België',
                      'US' => 'Verenigde Staten',
                      'AU' => 'Oostenrijk',
                      'LU' => 'Luxemburg',
                      'DE' => 'Duitsland',
                      'GW' => 'Duitsland'
                    );
                    if(isset($codes[$text])):
                      $string = $codes[$text];
                    else:
                      $string = $text;
                    endif;
                  endif;
                  echo str_replace("&amp;","&",$string);
                ?>
            </div>
        <?php endforeach; ?>
      </td>
    </tr>
<?php endforeach; ?>
