<div class="section section--no-padding section--6--light">
    <div class="container">
        <div class="grid grid--no-gutter">
            <div class="grid__12 grid__6@med flex flex-justify-center">
                <div class="panel panel--lrg panel--light u-pl-0">

                    <!-- breadcrumbs -->
                    <div class="breadcrumb spacer">
                        <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
                            <a href="<?php echo $block->page()->site()->url();?>" itemprop="url" class="breadcrumb__item"><span itemprop="title">Home</span></a>
                        </span>
                        <?php $nav = $block->page()->site()->publicNav();?>
                        <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
                        <?php if($nav->breadcrumbs() != ''): ?>
                          <?php echo $nav->breadcrumbs()->setSeparator('</span>
                          <span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">'
                          ); ; ?>
                        <?php else: ?>
                            <a href="" itemprop="url" class="breadcrumb__item breadcrumb__item--active"><span itemprop="title"><?php echo $block->page()->title();?></span></a>
                        <?php endif;?>
                        </span>
                    </div>
                    <h1 class="spacer"><?php echo $block->dataValue('title');?></h1>
                    <div class="text--lead spacer">
                        <?php echo $block->dataValue('text');?>
                    </div>
                    <?php if($block->dataValue('link')):?>
                        <div class="link link--ext spacer"><a href="<?php echo $block->dataValue('link');?>"><?php echo $block->dataValue('link_text');?></a></div>
                    <?php endif;?>
                </div>
            </div>

            <?php if(sizeof($attachments)>0):?>
              <div class="grid__12 grid__6@med">
                  <div class="image--secondary">
                    <?php
                      $media = $attachments[0]->media();
                      if($media):
                        echo $this->thumbnail($media, 'large',array('class' => 'u-display-block'));
                      endif;
                    ?>
                  </div>
                  <figcaption><?php echo $attachments[0]->caption();?></figcaption>
              </div>
            <?php endif;?>
        </div>
        </div>
    </div>
</div>
