<div class="section section--no-padding section--6--light">
    <div class="container">
        <div class="grid grid--no-gutter">
            <div class="grid__12 grid__6@med flex flex-justify-center">
                <div class="panel panel--lrg panel--light u-pl-0">
                    <!-- breadcrumbs -->
                    <div class="breadcrumb spacer">
                        <span itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
                            <a href="<?php echo "/";?>" itemprop="url" class="breadcrumb__item"><span itemprop="title">Home</span></a>
                        </span>
                        <?php
                          $bc = $block->page()->site()->publicNav()->breadcrumbs()->setSeparator('</span>
                            <span itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">'
                            )->setMinDepth(1);
                        ?>
                        <?php $bctest = strip_tags($bc).'test';?>
                        <span itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
                        <?php if(strip_tags($bctest) != 'test'):?>
                          <?php echo $bc;?>
                        <?php else: ?>
                          <span itemprop="title"><?php echo $block->page()->title();?></span>
                        <?php endif;?>
                        </span>
                    </div>
                    <h1 class="spacer"><?php echo $block->dataValue('title');?></h1>

                    <div class="text--lead spacer">
                        <?php echo $block->dataValue('text');?>
                    </div>
                </div>
            </div>

            <?php if(sizeof($attachments)>0):?>
              <div class="grid__12 grid__6@med">
                  <div class="image--secondary">
                    <?php
                      $media = $attachments[0]->media();
                      if($media):
                        $url = $media->thumbnailUrl('large');
                        $url = str_replace('http:', '', $url);
                        if($block->dataValue('itemurl')):
                          $itemUrl = $media->item()->url();
                          $itemUrl = str_replace('http:', '', $itemUrl);
                          ?>
                          <a href="<?php echo $itemUrl;?>"><img src="<?php echo $url;?>" class='u-display-block'></a>
                        <?php else:?>
                          <img src="<?php echo $url;?>" class='u-display-block'>
                        <?php endif;?>
                      <?php endif;
                    ?>
                  </div>
                  <figcaption><?php echo $attachments[0]->caption();?></figcaption>
              </div>
            <?php endif;?>
        </div>
        </div>
    </div>
</div>

<?php
function breadcrumb_temp($r, $title){
  $result = array();
  foreach($r as $page1):
    $parents = array();
    if($page1['label'] == $title):
      $result = $parents;
      return $result;
    endif;
    if(isset($page1['params'])):
      $parents[0] = ['label' => $page1['label'], 'slug' => "/page/".$page1['params']['page-slug']];
    else:
      $parents[0] = ['label' => $page1['label'], 'slug' => $page1['uri']];
    endif;

    foreach($page1['pages'] as $page2):
      unset($parents[1]);unset($parents[2]);unset($parents[3]);unset($parents[4]);
      if($page2['label'] == $title):
        $result = $parents;
        return $result;
        $parents = array();
      endif;
      if(isset($page2['params'])):
        $parents[1] = ['label' => $page2['label'], 'slug' => "/page/".$page2['params']['page-slug']];
      else:
        $parents[1] = ['label' => $page2['label'], 'slug' => $page2['uri']];
      endif;

      foreach($page2['pages'] as $page3):
        unset($parents[2]);unset($parents[3]);unset($parents[4]);
        if($page3['label'] == $title):
          $result = $parents;
          return $result;
          $parents = array();
        endif;
        if(isset($page3['params'])):
          $parents[2] = ['label' => $page3['label'], 'slug' => "/page/".$page3['params']['page-slug']];
        else:
          $parents[2] = ['label' => $page3['label'], 'slug' => $page3['uri']];
        endif;

        foreach($page3['pages'] as $page4):
          unset($parents[3]);  unset($parents[4]);
          if($page4['label'] == $title):
            $result = $parents;
            return $result;
            $parents = array();
          endif;
          if(isset($page4['params'])):
            $parents[3] = ['label' => $page4['label'], 'slug' => "/page/".$page4['params']['page-slug']];
          else:
            $parents[3] = ['label' => $page4['label'], 'slug' => $page4['uri']];
          endif;

          foreach($page4['pages'] as $page5):
            unset($parents[4]);
            if($page5['label'] == $title):
              $result = $parents;
              $parents = array();
              return $result;
            endif;
            if(isset($page5['params'])):
              $parents[4] = ['label' => $page5['label'], 'slug' => "/page/".$page5['params']['page-slug']];
            elseif(isset($page2['uri'])):
              $parents[4] = ['label' => $page5['label'], 'slug' => $page5['uri']];
            endif;
          endforeach;
        endforeach;
      endforeach;
    endforeach;
  endforeach;  //echo $nav;
}
?>
