<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response)) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchPage->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchPage->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayButton = $displayFacetButton ? $searchPage->subSetting('facet', 'display_button', 'above') : 'none';

$facetActive = $plugins->get('facetActive');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');
$facetSelectRange = $plugins->get('facetSelectRange');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchPage->setting('facet', []);
?>

<div class="grid__12 grid__4@med">
   <div class="panel panel--light">
    <h2>Filter <?php echo lcfirst($searchPage->name());?></h2>
        <?php if($query->getQuery()):?>
            <div class="current-query">
                Zoekopdracht: <a title="verwijder zoekopdracht" href="<?= parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH).'?q=' ?>"><?= htmlspecialchars($query->getQuery());?> <span class="icon icon--clear"></span></a></button>
            </div>
        <?php endif;?>
        <hr>
        <h4>Tekstueel zoeken</h4>
        <div class="spacer">
            <form>
            <?php //echo $this->searchForm(); ?>
            <div class="form__item">
                <input type="text" name="q" class="form__text" value="<?= htmlspecialchars($query->getQuery());?>">
            </div>
            <div class="form__actions">
                <button type="submit" class="btn form__btn">zoeken <span class="icon icon--search"></span></button>
            </div>
            </form>
        </div>    
        <hr>          
    <?php if(!empty($searchPage->subSetting('facet', 'facets'))):?>    
        <h3><?= $translate('Filters') ?></h3>
        <div class="spacer">    
            <?php if ($displayActive && count($activeFacets)): ?>
                <h4><?= $translate('Actieve filters') ?></h4>
            
                <div class="search-facets-active">
                    <?php foreach ($activeFacets as $name => $facetValues) foreach ($facetValues as $facetKey => $facetValue): ?>
                    <div><?= $facetActive($name, ['value' => $facetValue, 'count' => null, 'key' => $facetKey], $options) ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <form id="form-facets">

                <?php if ($displayFacetButton): ?>
                <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
                <?php endif; ?>

                <?php if ($displayFacetButton && ($displayButton === 'above' || $displayButton === 'both')): ?>
                <div class="apply-facets apply-facets-top" style="margin-bottom:1rem;">
                    <button id="apply-facets" class="btn form__btn active" type="submit"><?= $translate('Filters toepassen') ?></button>
                </div>
                <?php endif; ?>

                <?php if (empty($facets) && empty($activeFacets)): ?>
                <p><?= $translate('No facets.') ?></p>
                <?php else: ?>
                <div class="search-facets-list">
                    <?php foreach ($facets as $name => $facetValues): ?>
                    <?php $facetType = empty($options['facets'][$name]['type']) ? 'Checkbox' : $options['facets'][$name]['type']; ?>
                    <h4><?= $translate($facetLabel($name)) ?></h4>
                    <div class="form__group">
                        
                        <?php if ($facetType === 'Select'): ?>
                        <?= $facetSelect($name, $facetValues, $options) ?>
                        <?php elseif ($facetType === 'SelectRange'): ?>
                        <?= $facetSelectRange($name, $facetValues, $options) ?>
                        <?php else: ?>
                        <?= $facetElements($name, $facetValues, $options) ?>
                        <?php endif; ?>
                    </div>
                    <?php endforeach; ?>
                </div>
                <?php endif; ?>

                <?php if ($displayFacetButton && ($displayButton === 'below' || $displayButton === 'both')): ?>
                <div class="apply-facets apply-facets-bottom" style="margin-top:1rem;">
                    <button id="apply-facets" class="btn form__btn" type="submit"><?= $translate('Filters toepassen') ?></button>
                </div>
                <?php endif; ?>
            </form>
        </div>
    <?php endif;?>
</div>
</div>


