<div class="section section--lrg section--light">
  <div class="container">
    <div class="breadcrumb spacer">
    </div>
    <?php echo $this->pageTitle(sprintf($this->translate('Zoekresultaten “%s”'), htmlspecialchars($query))); ?>
  </div>
</div>
<?php if($pagesTotal):?>
<div class="section section--default">
  <div class="container">    
        <h2><?php echo $this->translate('Pages')."(".$pagesTotal.")"; ?></h2>
        <?php if ($pages): ?>
            <?php foreach ($pages as $page): ?>
            <div class="list_page">
              <h2 class="heading--3 card__title"><?php echo $page->link($page->title()); ?></h2>
            </div>
            <?php endforeach; ?>
        <div class="more_results">
          <?php echo $this->hyperlink(
              sprintf($this->translate("Bekijk alle pagina's (%s)"), $pagesTotal),
              $this->url(
                  'site/page-browse',
                  ['controller' => 'page', 'action' => 'browse'],
                  ['query' => ['fulltext_search' => htmlspecialchars($query)]],
                  true
              )
          ); ?>
          <?php else: ?>
          <p><?php echo $this->translate('Geen resultaten'); ?></p>
          <?php endif; ?>
        </div>
    </div>  
</div>
<?php endif;?> 
<div class="section section--default">
  <div class="container">
    <div class="grid__12">       

        <?php 
        
        $templates= array(
          "Beeldbank" => array("id" => "6","url" => "/beeldbank"),
          "Cinema Rural Filmdatabank" => array("id" => "10","url" => "/films"),
          "Collecties" => array("id" => "7","url" => "/collecties"),
          "Projecten" => array("id" => "2","url" => "/projecten"),
          "Verhalen" => array("id" => "3","url" => "/verhalen"),
          "Nieuws" => array("id" => "16","url" => "/nieuws"),
          "Agenda" => array("id" => "19","url" => "/agenda"),
        );

        parse_str("fulltext_search=".$query."&resource_template_id[]=6item_set_id[]=&site_id=&submit=Zoeken", $api_query);
        $api_query['limit'] = 200000;  

        $i = 0;
        foreach($templates as $label => $template):          
          $api_query['resource_template_id'] = $template["id"];
          $items = $this->api()->search('items', $api_query);
          $items = $items->getContent();
          
          if(sizeof($items)):
            $i++;
            if($i == 1):
              echo "<h2>".$this->translate('Items')." in onze databanken</h2>";
            endif;  

            echo '<div class="list_page">';
            echo '<h2 class="heading--3 card__title">';
            echo "<a href='".$template["url"]."?q=".$query."'>".$label." (".sizeof($items).")</a><br>";
            echo '</h2></div>';
          endif;
        endforeach;  
        
         
        if(!$pagesTotal && $i==0):
          echo "Geen resultaten";
        endif;  
        ?>  
        </div>
    </div>
  </div>
</div>
