<?php
$translate = $this->plugin('translate');
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
?>

<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'index','action' => 'search'], true)); ?>" class="search__form js-search-form js-search-container">
    <div class="form__item js-search-input">
        <input type="search" id="form-search" class="search__input form__text-underline js-search-focus" value="<?php echo $searchValue; ?>" name="fulltext_search" placeholder="Search">
        <button type="submit" class="btn btn--primary search__submit" aria-label="Search"><i class="icon icon--search hidden--bp-med"></i></button>
    </div>
    <a href="#" class="search__close"><i class="icon icon--clear"></i> <span class="visuallyhidden">Close</span></a>
</form>
