<?php
use Zend\Form\Element\Textarea;
?>
<?php echo $this->blockAttachmentsForm($block);?>
<p>
  All atachments will be shown in a horizontal gallery. Use the caption field of an attachment to add a link.
</p>
<h4>Title (optional title above the gallery)</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">
  </div>
</div>
