<?php
use Zend\Form\Element\Textarea;
?>
<?php echo $this->blockAttachmentsForm($block);?>
<p>
  There will a column/tile for every image/attachment, so 2 attachments will results in a 2 column block.
</p>
<h4>Title (optional title above the tiles)</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">
  </div>
</div>
