<!-- overview blocks -->
<?php if(sizeof($attachments) > 2):
  $number = rand(0,999999);
?>
<div class="section section--default column-block">

    <div class="container">
        <h2><?php echo $block->dataValue('title');?></h2>
        <?php echo $block->dataValue('text');?>
        <div class="gallery-<?php echo $number;?>">
          <?php foreach($attachments as $attachment){ ?>
            <div>
                <?php
                  $text="";$link="";
                  if($attachment->caption()):
                    preg_match_all("/\[([^\]]*)\]/", $attachment->caption(), $matches);
                    $text = $matches[1];

                    $link = preg_replace('`\[[^\]]*\]`','', $attachment->caption());;
                    $link = trim(strip_tags($link));
                  endif;
                ?>
                <?php if($link):?>
                <a href="<?php echo $link;?>">
                <?php endif;?>
                <?php
                  $url='';
                  $media = $attachment->media();
                  if($media):
                    $url = $media->thumbnailUrl('medium');
                    $url = str_replace('http:', '', $url);
                  endif;
                ?>
                <img src="<?php echo  $url;?>">
                <?php if($link):?>
                </a>
                <?php endif;?>
                <?php if($text):?>
                  <div class="caption">
                    <?php print_r($text[0]);?>
                  </div>
                <?php endif;?>
            </div>
          <?php } ?>
        </div>
    </div>
</div>
<?php else:?>
  <p>
    Om dit blok te gebruiken moet je minstens 3 afbeeldingen (attachments) selecteren.
  </p>
<?php endif;?>
<?php
  if(sizeof($attachments) < 5):
    $slidesToShow = sizeof($attachments) - 1;
  else:
    $slidesToShow = 4;
  endif;
?>
<script>
$('.gallery-<?php echo $number;?>').slick({
  dots: false,
  infinite: true,
  speed: 300,
  slidesToShow: <?php echo $slidesToShow;?>,
  slidesToScroll: <?php echo $slidesToShow;?>,
  centerMode: true,
  variableWidth: true,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: <?php echo $slidesToShow - 1;?>,
        slidesToScroll: <?php echo $slidesToShow - 1;?>
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
  ]
});
</script>
