<?php
$translate = $this->plugin('translate');
?>

<div class="section section--default">
  <div class="container">

    <?php if ($this->heading): ?>
    <h2><?php echo $this->heading; ?></h2>
    <?php endif; ?>

    <?php if($block->dataValue('text')):?>
    <div class="grid spacer">
        <div class="grid__12 grid__8@med">
            <?php echo $block->dataValue('text');?>
        </div>
    </div>
    <?php endif; ?>

    <?php if($this->resources):?>
    <div class="grid grid--<?php echo $block->dataValue('columns');?>-col@med spacer--xsm">
      <?php
      $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
      $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
      $templates = array(
        'Beeld' => 'beeldbank',
        'Verhaal' => 'verhalen',
        'Project' => 'projecten',
        'Film' => 'films',
        'Filmkopie' => 'filmkopies',
        'Collecite' => 'collecties',
        'Nieuws' => 'nieuws',
        'Agendapunt' => 'agenda',
        'Agendapunt BKV' => 'agenda-bkv',
        'Nieuws BKV' => 'nieuws-bkv',
        'Object BKV' => 'objecten'
      );
      foreach ($this->resources as $resource):
          $heading = $resource->value($headingTerm, ['default' => $translate('[Untitled]')]);
          $body = $resource->value($bodyTerm);
          $type = $resource->resourceTemplate();
          if($type):
            $type= $type->label();
          else:
            $type= "Object";
          endif;
      ?>
      <div class="grid__item">
        <div class="card card--gray card--clickable card--link card--variant2">
            <?php
              $media = $resource->media();
              if($media):
                if(sizeof($this->resources) <= 2):
                  $mediaurl = $media[0]->thumbnailUrl('large');
                  $mediaurl = str_replace('http:', '', $mediaurl);
                else:
                  $mediaurl = $media[0]->thumbnailUrl('medium');
                  $mediaurl = str_replace('http:', '', $mediaurl);
                endif;
              else:
                $mediaurl = "";
              endif;

              if($type == 'Verhaal' || $type == 'Project' || $type == 'Agendapunt BKV' || $type == 'Nieuws BKV' || $type == 'Object BKV'):
                $url = "/page/".$resource->value('dcterms:relation');
              else:
                $url = $resource->url();
                $date = '';
              endif;
            ?>
            <a href="<?php echo $url;?>">
              <div class="card__img card__img_3"
                style="background:url(<?php echo  $mediaurl;?>) no-repeat center center;background-color:#7fb5b2;background-size: cover;"
                >
              </div>
              <div class="card__body panel panel--light">
                <?php if($type == 'Project'):?>
                  <div style="margin-bottom:13px;" class="label spacer"><?php echo $type;?></div>
                <?php endif;?>
                <h2 class="heading--3 card__title spacer--xsm">
                  <a href="<?php echo $url;?>"><?php echo $resource->value('dcterms:title');?></a>
                </h2>

                <?php if($resource->value('dcterms:date') && ($type == 'Nieuws' || $type == 'Agendapunt' || $type == 'Agendapunt BKV' || $type == 'Nieuws BKV')):?>
                    <?php
                      $date = $resource->value('dcterms:date');
                      //echo $date;
                      $output = DateTime::createFromFormat('Ymd', $date);
                      if(!$output){
                          $output = DateTime::createFromFormat('Y-m-d', $date);
                      }
                      $output = $output->format('d-m-Y');
                    ?>
                    <p class="datering"><?php echo $output;?></p>
                <?php endif;?>
                <?php if ($body): ?>
                  <?php
                    if(strlen(strip_tags($body)) > 200):
                      $body = substr(strip_tags($body), 0, 200);
                      $body = substr($body, 0, strrpos($body, ' ')).' ...';
                    endif;
                  ?>
                  <p>
                    <?php echo $body; ?>
                  </p>
                <?php endif; ?>
                <div class="link link--ext card__link">
                  <?php
                    $typel = $type;
                    if($type == 'Agendapunt BKV'):
                      $typel = 'Activiteit';
                    endif;
                    if($type == 'Nieuws BKV'):
                      $typel = 'Nieuwsbericht';
                    endif;
                    if($type == 'Object BKV'):
                      $typel = 'Object';
                    endif;
                  ?>
                  <?php if($type == 'Film' || $type == 'Filmkopie'):?>
                    <a href="<?php echo $url;?>">Lees meer</a>
                  <?php else:?>
                    <a href="<?php echo $url;?>"><?php echo $typel.' bekijken';?></a>
                  <?php endif; ?>
                </div>
              </div>
            </a>
        </div>
      </div>
      <?php endforeach; ?>
    </div>
    <?php if ($this->linkText):?>
      <div class="text--center u-mt-med">
        <?php if($type == 'Nieuws' || $type == 'Agendapunt' || $type == 'Agendapunt BKV' || $type == 'Nieuws BKV'):?>
          <a href="<?php echo '/'.$templates[$type].'?q=&sort=dcterms:date desc'?>" class="btn btn--ext">
            <?php echo $this->linkText;?>
          </a>
        <?php else:?>
          <a href="<?php echo '/'.$templates[$type].'?q='?>" class="btn btn--ext">
            <?php echo $this->linkText;?>
          </a>
        <?php endif;?>
      </div>
    <?php endif;?>
    <?php endif;?>
  </div>

</div>
